default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") { db } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { poostgres } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { '' } %>
  port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>

development:
  <<: *default
  database: rl_mix_development

test:
  <<: *default
  database: rl_mix_test

production:
  <<: *default
  database: rl_mix_production
